name: CI
on:
  push:
    paths-ignore:
      - "**/README.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          
      - name: Run Kotlin Linter
        run: chmod +x runChecks.sh

      - name: Run Unit Tests
        run: ./gradlew test
